services:
  - type: web
    name: Braille-Assistive-Reader
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      ./build.sh
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
